### ISSUE TITLE
[REQUEST] FontAwesome?

### ISSUE THREAD

**Issue by irobayna** [fandogh/nuxt-helpers#1]
@pi0 First of all, thank you for maintaining nuxt-helpers.  I am a newbie and they sure help me adding new functionality in a straightforward manner.

Any plans for other helpers?  How about FontAwesome?

Not sure how involved it is to add a new helper. If you are willing to guide me I would be happy to submit a Pull Request.

Thanks

**Comment by pi0** [comment]
@irobayna Thanks for your interest. Yep we can easily add a helper function for that. Steps including:
- adding [ font-awesome](https://www.npmjs.com/package/font-awesome) dependency
- creating plugins/font-awesome.js  which exports an extend function (see extend in nuxt docs) that adds css to nuxt css array
- require and adding to install.js
- updating README

please let me know if you are willing/need help doing steps above :)
