### ISSUE TITLE
bootstrap helper - automatically include css?

### ISSUE THREAD

**Issue by irobayna** [fandogh/nuxt-helpers#5]
If the ```font-awesome``` helper already includes the needed css, shouldn't the ```bootstrap``` helper also do the same thing?

It appears right now the boostrap css must be loaded somehow (I am including it via ```nuxt.config.js```

**Comment by pi0** [comment]
@irobayna This was intentional  by design for both `nuxt-helpers` and `bootstrap-vue` projects. If we include bootstrap that way developers can't customize bootstrap builds (themes for example). Anyway i agree with you we can add another helper like `boostrap-css` that does this.

**Comment by irobayna** [comment]
makes sense!
